version: '3.4'

x-anchors:
  antalla_config: &antalla_config
    image: samwerner/antalla
    env_file:
      - config/antalla.env

services:
  coinbase:
    <<: *antalla_config
    command:
      - run
      - --exchange
      - coinbase
      - --event-type
      - trade
      - --markets-files
      - data/btc_markets/btc-markets.json
      - data/eth_markets/eth-markets.json

  hitbtc:
    <<: *antalla_config
    command:
      - run
      - --exchange
      - hitbtc
      - --event-type
      - trade
      - --markets-files
      - data/btc_markets/btc-markets.json
      - data/eth_markets/eth-markets.json

  idex:
    <<: *antalla_config
    command:
      - run
      - --exchange
      - idex
      - --event-type
      - trade
      - --markets-files
      - data/eth_markets/eth-markets.json

  binance:
    <<: *antalla_config
    command:
      - run
      - --exchange
      - binance
      - --event-type
      - trade
      - --markets-files
      - data/btc_markets/btc-markets.json
      - data/eth_markets/eth-markets.json
