# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: antalla
          POSTGRES_DB: antalla
          POSTGRES_PASSWORD: antalla

    working_directory: ~/antalla

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
 
      - run:
          name: setup project
          command: |
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: initialize database
          command: |
            . venv/bin/activate
            antalla migrations upgrade head

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            nosetests --with-doctest

      - store_artifacts:
          path: test-reports
          destination: test-reports
