title: Antalla
email: daniel@dudo.tech
description: A cryptocurrency exchange market data aggregator

logo: assets/images/logo_2.svg

baseurl: ""
url: "https://antalla.dudo.tech"

markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
